Repository r-staceans/blazr, pull requests merged in 2024-12, with the labels that each got.

#1 🎉 gains initial R package scaffolding
  .Rbuildignore
  .github/.gitignore
  .github/CONTRIBUTING.md
  .github/workflows/R-CMD-check.yaml
  .github/workflows/pkgdown.yaml
  .github/workflows/pr-commands.yaml
  .github/workflows/test-coverage.yaml
  .gitignore
  DESCRIPTION
  LICENSE
  LICENSE.md
  NAMESPACE
  R/add.R
  R/multiverse-package.R
  README.md
  _pkgdown.yml
  codecov.yml
  man/multiverse-package.Rd
  multiverse.Rproj
  tests/testthat.R
  tests/testthat/test-add.R
Labels: upkeep

#17 GH actions for rendering of README.Rmd
  .github/workflows/render-rmarkdown.yaml
Labels: upkeep

#20 🎨 upkdate `pkgdown` theme
  _pkgdown.yml
  pkgdown/favicon/apple-touch-icon.png
  pkgdown/favicon/favicon-96x96.png
  pkgdown/favicon/favicon.ico
  pkgdown/favicon/favicon.svg
  pkgdown/favicon/site.webmanifest
  pkgdown/favicon/web-app-manifest-192x192.png
  pkgdown/favicon/web-app-manifest-512x512.png
Labels: documentation

#19 ✨ gains `sum_with_threads`
  NAMESPACE
  R/000-wrappers.R
  README.Rmd
  README.md
  man/blazr-package.Rd
  man/figures/README-benchmark-1.png
  man/int_times_int.Rd
  man/sum_with_threads.Rd
  man/to_upper.Rd
  src/init.c
  src/rust/Cargo.lock
  src/rust/Cargo.toml
  src/rust/api.h
  src/rust/src/lib.rs
  tests/testthat/test-add.R
  tests/testthat/test-sum_with_threads.R
Labels: feature

#27 🐛 format `DESCRIPTION`
  DESCRIPTION
  man/blazr-package.Rd
Labels: bug

#25 ✨ gains numeric `sum_with_threads`
  src/rust/src/lib.rs
  tests/testthat/test-sum_with_threads.R
Labels: feature

#29 📋 `DESCRIPTION` gains title and description
  DESCRIPTION
  man/blazr-package.Rd
Labels: documentation
